GET http://localhost:3000/

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users/create
Content-Type: application/json

{
    "nickname":"Pepa0",
    "email":"pepa@ucm.es",
    "password":"123456"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"pepa@ucm.es",
    "password":"123456"
}

//GetAllConcepts 
###
GET http://localhost:3000/concepts


//GetAllPosts
###
GET http://localhost:3000/posts

//GetByPostId
###
GET http://localhost:3000/posts/6

###
GET http://localhost:3000/search?searchTerm=Nación&&blogs=1&&blogs=2&&concepts=all


###
GET http://localhost:3000/tests/1/questions


//paginación de los conceptos
###
GET http://localhost:3000/concepts/page/0


//paginación de los conceptos
###
POST http://localhost:3000/concepts/favorite
Content-Type: application/json


{
    "idconcepto":1
}
