GET http://localhost:3000/

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users/create
Content-Type: application/json

{
    "nickname":"Pepa0",
    "email":"pepa@ucm.es",
    "password":"123456"
}


//GetAllConcepts 
###
GET http://localhost:3000/concepts


//GetAllPosts
###
GET http://localhost:3000/posts

//GetByPostId
###
GET http://localhost:3000/posts/3


Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoicGVwYUB1Y20uZXMiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE2MDczNTkxNTEsImV4cCI6MTYwNzUzMTk1MX0.At4POv7YleTOFiU2oziYFOqutzIjQfbwFjFzLuyCD98